/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframetest;

/**
 *
 * @author Wendler
 */
public class CadastroPaciente extends javax.swing.JFrame {

    /**
     * Creates new form CadastroPaciente
     */
    public CadastroPaciente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroFuncionario = new javax.swing.JPanel();
        jTextFieldCadastroNomePaciente = new javax.swing.JTextField();
        jLabelCadastraCrfPaciente = new javax.swing.JLabel();
        jTextFieldCadastroCrfPaciente = new javax.swing.JTextField();
        jToggleButtonCadastraPaciente = new javax.swing.JToggleButton();
        jToggleButtonCadastroCancelaPaciente = new javax.swing.JToggleButton();
        jLabelCadastroNomePaciente = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelCadastroFuncionario.setPreferredSize(new java.awt.Dimension(418, 365));

        jTextFieldCadastroNomePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroNomePacienteActionPerformed(evt);
            }
        });

        jLabelCadastraCrfPaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastraCrfPaciente.setText("Digite o CPF");

        jToggleButtonCadastraPaciente.setText("Cadastra");
        jToggleButtonCadastraPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastraPacienteActionPerformed(evt);
            }
        });

        jToggleButtonCadastroCancelaPaciente.setText("Cancela");
        jToggleButtonCadastroCancelaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastroCancelaPacienteActionPerformed(evt);
            }
        });

        jLabelCadastroNomePaciente.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastroNomePaciente.setText("Digite o Nome");

        javax.swing.GroupLayout jPanelCadastroFuncionarioLayout = new javax.swing.GroupLayout(jPanelCadastroFuncionario);
        jPanelCadastroFuncionario.setLayout(jPanelCadastroFuncionarioLayout);
        jPanelCadastroFuncionarioLayout.setHorizontalGroup(
            jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                        .addComponent(jLabelCadastraCrfPaciente)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(jToggleButtonCadastraPaciente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jToggleButtonCadastroCancelaPaciente))
                            .addComponent(jTextFieldCadastroNomePaciente)
                            .addComponent(jTextFieldCadastroCrfPaciente, javax.swing.GroupLayout.DEFAULT_SIZE, 358, Short.MAX_VALUE)
                            .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                                .addComponent(jLabelCadastroNomePaciente)
                                .addGap(0, 272, Short.MAX_VALUE)))
                        .addGap(30, 30, 30))))
        );
        jPanelCadastroFuncionarioLayout.setVerticalGroup(
            jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                .addContainerGap(79, Short.MAX_VALUE)
                .addComponent(jLabelCadastroNomePaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCadastroNomePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jLabelCadastraCrfPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCadastroCrfPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonCadastraPaciente)
                    .addComponent(jToggleButtonCadastroCancelaPaciente))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCadastroFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 345, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jToggleButtonCadastroCancelaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastroCancelaPacienteActionPerformed
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonCadastroCancelaPacienteActionPerformed

    private void jToggleButtonCadastraPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastraPacienteActionPerformed
        //CadastroSucesso cadastroSucesso = new CadastroSucesso();
        Confirmacao confirmacao = new Confirmacao();
        confirmacao.setVisible(true);
        confirmacao.setLocationRelativeTo(null);
        confirmacao.setDefaultCloseOperation(confirmacao.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jToggleButtonCadastraPacienteActionPerformed

        pack();
    }// </editor-fold>                        

    private void jTextFieldCadastroNomePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroNomePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroNomePacienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelCadastraCrfPaciente;
    private javax.swing.JLabel jLabelCadastroNomePaciente;
    private javax.swing.JPanel jPanelCadastroFuncionario;
    private javax.swing.JTextField jTextFieldCadastroCrfPaciente;
    private javax.swing.JTextField jTextFieldCadastroNomePaciente;
    private javax.swing.JToggleButton jToggleButtonCadastraPaciente;
    private javax.swing.JToggleButton jToggleButtonCadastroCancelaPaciente;
    // End of variables declaration//GEN-END:variables
}
