/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jframetest;

/**
 *
 * @author Wendler
 */
public class CadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form CadastroFuncionario
     */
    public CadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCadastroFuncionario = new javax.swing.JPanel();
        jTextFieldCadastroNomeFuncionario = new javax.swing.JTextField();
        jLabelCadastraCrfFuncionario1 = new javax.swing.JLabel();
        jTextFieldCadastroCrfFuncionario1 = new javax.swing.JTextField();
        jLabelCadastroEspecialidadeFuncionario1 = new javax.swing.JLabel();
        jComboBoxCadsatraEspecialidadeFuncionario1 = new javax.swing.JComboBox();
        jToggleButtonCadastraFuncionario = new javax.swing.JToggleButton();
        jToggleButtonCadastroCancelaFuncionario = new javax.swing.JToggleButton();
        jLabelCadastroNomeFuncionario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelCadastroFuncionario.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanelCadastroFuncionario.setPreferredSize(new java.awt.Dimension(418, 365));

        jTextFieldCadastroNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCadastroNomeFuncionarioActionPerformed(evt);
            }
        });

        jLabelCadastraCrfFuncionario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastraCrfFuncionario1.setText("Digite o CRF");

        jLabelCadastroEspecialidadeFuncionario1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastroEspecialidadeFuncionario1.setText("Selecione sua Especialidade");

        jComboBoxCadsatraEspecialidadeFuncionario1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muscular", "Pilates", "Fisioterapeuta Manual", "Acunpultura" }));
        jComboBoxCadsatraEspecialidadeFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCadsatraEspecialidadeFuncionario1ActionPerformed(evt);
            }
        });

        jToggleButtonCadastraFuncionario.setText("Cadastra");
        jToggleButtonCadastraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastraFuncionarioActionPerformed(evt);
            }
        });

        jToggleButtonCadastroCancelaFuncionario.setText("Cancela");
        jToggleButtonCadastroCancelaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCadastroCancelaFuncionarioActionPerformed(evt);
            }
        });

        jLabelCadastroNomeFuncionario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelCadastroNomeFuncionario.setText("Digite o Nome");

        javax.swing.GroupLayout jPanelCadastroFuncionarioLayout = new javax.swing.GroupLayout(jPanelCadastroFuncionario);
        jPanelCadastroFuncionario.setLayout(jPanelCadastroFuncionarioLayout);
        jPanelCadastroFuncionarioLayout.setHorizontalGroup(
            jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                        .addComponent(jToggleButtonCadastraFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jToggleButtonCadastroCancelaFuncionario))
                    .addComponent(jTextFieldCadastroNomeFuncionario)
                    .addComponent(jComboBoxCadsatraEspecialidadeFuncionario1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCadastroCrfFuncionario1)
                    .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                        .addGroup(jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelCadastroEspecialidadeFuncionario1)
                            .addComponent(jLabelCadastraCrfFuncionario1)
                            .addComponent(jLabelCadastroNomeFuncionario))
                        .addGap(0, 192, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        jPanelCadastroFuncionarioLayout.setVerticalGroup(
            jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCadastroFuncionarioLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabelCadastroNomeFuncionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCadastroNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCadastraCrfFuncionario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCadastroCrfFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelCadastroEspecialidadeFuncionario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxCadsatraEspecialidadeFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(jPanelCadastroFuncionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jToggleButtonCadastraFuncionario)
                    .addComponent(jToggleButtonCadastroCancelaFuncionario))
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanelCadastroFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldCadastroNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCadastroNomeFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCadastroNomeFuncionarioActionPerformed

    private void jComboBoxCadsatraEspecialidadeFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCadsatraEspecialidadeFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCadsatraEspecialidadeFuncionario1ActionPerformed

    private void jToggleButtonCadastraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastraFuncionarioActionPerformed
        //CadastroSucesso cadastroSucesso = new CadastroSucesso();
        Confirmacao confirmacao = new Confirmacao();
        confirmacao.setVisible(true);
        confirmacao.setLocationRelativeTo(null);
        confirmacao.setDefaultCloseOperation(confirmacao.DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_jToggleButtonCadastraFuncionarioActionPerformed

    private void jToggleButtonCadastroCancelaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCadastroCancelaFuncionarioActionPerformed
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jToggleButtonCadastroCancelaFuncionarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBoxCadsatraEspecialidadeFuncionario1;
    private javax.swing.JLabel jLabelCadastraCrfFuncionario1;
    private javax.swing.JLabel jLabelCadastroEspecialidadeFuncionario1;
    private javax.swing.JLabel jLabelCadastroNomeFuncionario;
    private javax.swing.JPanel jPanelCadastroFuncionario;
    private javax.swing.JTextField jTextFieldCadastroCrfFuncionario1;
    private javax.swing.JTextField jTextFieldCadastroNomeFuncionario;
    private javax.swing.JToggleButton jToggleButtonCadastraFuncionario;
    private javax.swing.JToggleButton jToggleButtonCadastroCancelaFuncionario;
    // End of variables declaration//GEN-END:variables
}
