/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JComboBox;


/**
 *
 * @author Wendler
 */
public class Funcionario extends javax.swing.JFrame {
    private String nomeFuncionario, crfFuncionario;
    

    public String getCrfFuncionario() {
        return crfFuncionario;
    }

    public void setCrfFuncionario(String crfFuncionario) {
        this.crfFuncionario = crfFuncionario;
    }

    public String getNomeFuncionario() {
        return nomeFuncionario;
    }

    public void setNomeFuncionario(String nomeMedico) {
        this.nomeFuncionario = nomeFuncionario;
    }
    /**
     * Creates new form Medico
     */
    public Funcionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTabbedPaneFuncionario = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabelNomeFuncionario2 = new javax.swing.JLabel();
        jTextFieldNomeFuncionario2 = new javax.swing.JTextField();
        jLabeCrfFuncionario1 = new javax.swing.JLabel();
        jTextFieldCrfFuncionario1 = new javax.swing.JTextField();
        jLabelEspecialidadeFuncionario1 = new javax.swing.JLabel();
        jComboBoxEspecialidadeFuncionario1 = new javax.swing.JComboBox();
        jButtonConfirmaAlteraFuncionario = new javax.swing.JButton();
        jButtonCancelarAlteraFuncionario = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jCheckBoxProcurarFuncionarioPorCRF = new javax.swing.JCheckBox();
        jCheckBoxProcurarFuncionarioPorNome = new javax.swing.JCheckBox();
        jCheckBoxProcurarFuncionarioPorEspecialidade = new javax.swing.JCheckBox();
        jTextFieldNomeFuncionario3 = new javax.swing.JTextField();
        jTextFieldCrfFuncionario3 = new javax.swing.JTextField();
        jComboBoxEspecialidadeFuncionario2 = new javax.swing.JComboBox();
        jButtonConfirmaProcuraFuncionario = new javax.swing.JButton();
        jButtonCancelarProcuraFuncionario = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jTextFieldCrfFuncionario2 = new javax.swing.JTextField();
        jLabeCrfFuncionario2 = new javax.swing.JLabel();
        jButtonDeletaFuncionario = new javax.swing.JButton();
        jButtonDeletarCancelarFuncionario = new javax.swing.JButton();
        jPanel11 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonAgendaConfirmaPaciente = new javax.swing.JButton();
        jButtonAgendaCancelarPaciente = new javax.swing.JButton();
        jPanel15 = new javax.swing.JPanel();
        jTextFieldCrfFuncionario4 = new javax.swing.JTextField();
        jLabeCrfFuncionario3 = new javax.swing.JLabel();
        jButtonConfirmaFuncionario1 = new javax.swing.JButton();
        jButtonCancelarFuncionario1 = new javax.swing.JButton();

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem vindo ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(209, Short.MAX_VALUE))
        );

        jTabbedPaneFuncionario.addTab("Tela Inicial", jPanel1);

        jLabelNomeFuncionario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelNomeFuncionario2.setText("Digite o novo Nome");

        jTextFieldNomeFuncionario2.setText("Nome");
        jTextFieldNomeFuncionario2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFuncionario2ActionPerformed(evt);
            }
        });

        jLabeCrfFuncionario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeCrfFuncionario1.setText("Digite o novo CRF");

        jTextFieldCrfFuncionario1.setText("CRF");

        jLabelEspecialidadeFuncionario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEspecialidadeFuncionario1.setText("Selecione sua nova Especialidade");

        jComboBoxEspecialidadeFuncionario1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muscular", "Pilates", "Fisioterapeuta Manual", "Acunpultura" }));

        jButtonConfirmaAlteraFuncionario.setText("Alterar");
        jButtonConfirmaAlteraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaAlteraFuncionarioActionPerformed(evt);
            }
        });

        jButtonCancelarAlteraFuncionario.setText("Cancelar");
        jButtonCancelarAlteraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAlteraFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEspecialidadeFuncionario1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldCrfFuncionario1)
                            .addComponent(jTextFieldNomeFuncionario2)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabeCrfFuncionario1)
                                    .addComponent(jLabelNomeFuncionario2)
                                    .addComponent(jLabelEspecialidadeFuncionario1))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(20, 20, 20))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonConfirmaAlteraFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarAlteraFuncionario)
                        .addGap(30, 30, 30))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelNomeFuncionario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabeCrfFuncionario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCrfFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelEspecialidadeFuncionario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxEspecialidadeFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaAlteraFuncionario)
                    .addComponent(jButtonCancelarAlteraFuncionario))
                .addGap(20, 20, 20))
        );

        jTabbedPaneFuncionario.addTab("Altera Funcionario", jPanel6);

        jCheckBoxProcurarFuncionarioPorCRF.setText("Pesquisar por CRF");
        jCheckBoxProcurarFuncionarioPorCRF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProcurarFuncionarioPorCRFActionPerformed(evt);
            }
        });

        jCheckBoxProcurarFuncionarioPorNome.setText("Pesquisar por Nome");
        jCheckBoxProcurarFuncionarioPorNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProcurarFuncionarioPorNomeActionPerformed(evt);
            }
        });

        jCheckBoxProcurarFuncionarioPorEspecialidade.setText("Procurar por Especialidade");
        jCheckBoxProcurarFuncionarioPorEspecialidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxProcurarFuncionarioPorEspecialidadeActionPerformed(evt);
            }
        });

        jTextFieldNomeFuncionario3.setText("Nome");
        jTextFieldNomeFuncionario3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeFuncionario3ActionPerformed(evt);
            }
        });

        jTextFieldCrfFuncionario3.setText("CRF");

        jComboBoxEspecialidadeFuncionario2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Muscular", "Pilates", "Fisioterapeuta Manual", "Acunpultura" }));

        jButtonConfirmaProcuraFuncionario.setText("Procurar");
        jButtonConfirmaProcuraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaProcuraFuncionarioActionPerformed(evt);
            }
        });

        jButtonCancelarProcuraFuncionario.setText("Cancelar");
        jButtonCancelarProcuraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarProcuraFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jCheckBoxProcurarFuncionarioPorEspecialidade)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxEspecialidadeFuncionario2, 0, 378, Short.MAX_VALUE)
                            .addComponent(jTextFieldCrfFuncionario3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addComponent(jTextFieldNomeFuncionario3, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBoxProcurarFuncionarioPorCRF)
                                    .addComponent(jCheckBoxProcurarFuncionarioPorNome))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonConfirmaProcuraFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarProcuraFuncionario)
                        .addGap(30, 30, 30))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jCheckBoxProcurarFuncionarioPorNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldNomeFuncionario3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 4, Short.MAX_VALUE)
                .addComponent(jCheckBoxProcurarFuncionarioPorCRF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCrfFuncionario3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addComponent(jCheckBoxProcurarFuncionarioPorEspecialidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBoxEspecialidadeFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaProcuraFuncionario)
                    .addComponent(jButtonCancelarProcuraFuncionario))
                .addGap(20, 20, 20))
        );

        jTabbedPaneFuncionario.addTab("Procura Funcionario", jPanel7);

        jTextFieldCrfFuncionario2.setText("CRF");

        jLabeCrfFuncionario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeCrfFuncionario2.setText("Digite o CRF do funcionário que deseja remover");

        jButtonDeletaFuncionario.setText("Deletar");
        jButtonDeletaFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletaFuncionarioActionPerformed(evt);
            }
        });

        jButtonDeletarCancelarFuncionario.setText("Cancelar");
        jButtonDeletarCancelarFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarCancelarFuncionarioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCrfFuncionario2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabeCrfFuncionario2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButtonDeletaFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDeletarCancelarFuncionario)
                        .addGap(10, 10, 10)))
                .addGap(20, 20, 20))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(72, Short.MAX_VALUE)
                .addComponent(jLabeCrfFuncionario2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldCrfFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDeletaFuncionario)
                    .addComponent(jButtonDeletarCancelarFuncionario))
                .addGap(20, 20, 20))
        );

        jTabbedPaneFuncionario.addTab("Deleta Funcionario", jPanel10);

        jButton1.setText("Verificar Dia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

//        jButtonAgendaConfirmaPaciente.setText("Confirmar");
//        jButtonAgendaConfirmaPaciente.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButtonAgendaConfirmaPacienteActionPerformed(evt);
//            }
//        });

        jButtonAgendaCancelarPaciente.setText("Cancelar");
        jButtonAgendaCancelarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaCancelarPacienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addContainerGap(96, Short.MAX_VALUE))
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jButtonAgendaConfirmaPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAgendaCancelarPaciente)
                .addGap(30, 30, 30))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonAgendaCancelarPaciente)
                    .addComponent(jButtonAgendaConfirmaPaciente))
                .addContainerGap())
        );

        jTabbedPaneFuncionario.addTab("Verifica Agenda", jPanel11);

        jTextFieldCrfFuncionario4.setText("Nome Paciente");
        jTextFieldCrfFuncionario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrfFuncionario4ActionPerformed(evt);
            }
        });

        jLabeCrfFuncionario3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeCrfFuncionario3.setText("Digite o nome do Paciente");

        jButtonConfirmaFuncionario1.setText("Confirmar");
        jButtonConfirmaFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaFuncionario1ActionPerformed(evt);
            }
        });

        jButtonCancelarFuncionario1.setText("Cancelar");
        jButtonCancelarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarFuncionario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jButtonConfirmaFuncionario1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonCancelarFuncionario1)
                .addGap(30, 30, 30))
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldCrfFuncionario4, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabeCrfFuncionario3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabeCrfFuncionario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCrfFuncionario4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaFuncionario1)
                    .addComponent(jButtonCancelarFuncionario1))
                .addGap(20, 20, 20))
        );

        jTabbedPaneFuncionario.addTab("Avaliação de Desempenho", jPanel15);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneFuncionario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPaneFuncionario)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonCancelarFuncionario1ActionPerformed

    private void jButtonConfirmaFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaFuncionario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmaFuncionario1ActionPerformed

    private void jTextFieldCrfFuncionario4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCrfFuncionario4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCrfFuncionario4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new Picker().chamaCalendario(jTextField1);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonDeletarCancelarFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarCancelarFuncionarioActionPerformed
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonDeletarCancelarFuncionarioActionPerformed

    private void jButtonDeletaFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletaFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonDeletaFuncionarioActionPerformed

    private void jButtonCancelarProcuraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarProcuraFuncionarioActionPerformed
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarProcuraFuncionarioActionPerformed

    private void jButtonConfirmaProcuraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaProcuraFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmaProcuraFuncionarioActionPerformed

    private void jTextFieldNomeFuncionario3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFuncionario3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFuncionario3ActionPerformed

    private void jCheckBoxProcurarFuncionarioPorEspecialidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProcurarFuncionarioPorEspecialidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProcurarFuncionarioPorEspecialidadeActionPerformed

    private void jCheckBoxProcurarFuncionarioPorNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProcurarFuncionarioPorNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProcurarFuncionarioPorNomeActionPerformed

    private void jCheckBoxProcurarFuncionarioPorCRFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxProcurarFuncionarioPorCRFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxProcurarFuncionarioPorCRFActionPerformed

    private void jButtonCancelarAlteraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarAlteraFuncionarioActionPerformed
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonCancelarAlteraFuncionarioActionPerformed

    private void jButtonConfirmaAlteraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmaAlteraFuncionarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonConfirmaAlteraFuncionarioActionPerformed

    private void jTextFieldNomeFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeFuncionario2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeFuncionario2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

//    private void jButtonAgendaConfirmaPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaConfirmaPacienteActionPerformed
//        HorarioAgendado TelaHorarioAgendado = new HorarioAgendado();
//        TelaHorarioAgendado.setVisible(true);
//        this.dispose();
//    }//GEN-LAST:event_jButtonAgendaConfirmaPacienteActionPerformed

    private void jButtonAgendaCancelarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaCancelarPacienteActionPerformed
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButtonAgendaCancelarPacienteActionPerformed
    
    public static void main(String args[]) {
        
     
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Funcionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Funcionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgendaCancelarPaciente;
    private javax.swing.JButton jButtonAgendaConfirmaPaciente;
    private javax.swing.JButton jButtonCancelarAlteraFuncionario;
    private javax.swing.JButton jButtonCancelarFuncionario1;
    private javax.swing.JButton jButtonCancelarProcuraFuncionario;
    private javax.swing.JButton jButtonConfirmaAlteraFuncionario;
    private javax.swing.JButton jButtonConfirmaFuncionario1;
    private javax.swing.JButton jButtonConfirmaProcuraFuncionario;
    private javax.swing.JButton jButtonDeletaFuncionario;
    private javax.swing.JButton jButtonDeletarCancelarFuncionario;
    private javax.swing.JCheckBox jCheckBoxProcurarFuncionarioPorCRF;
    private javax.swing.JCheckBox jCheckBoxProcurarFuncionarioPorEspecialidade;
    private javax.swing.JCheckBox jCheckBoxProcurarFuncionarioPorNome;
    private javax.swing.JComboBox jComboBoxEspecialidadeFuncionario1;
    private javax.swing.JComboBox jComboBoxEspecialidadeFuncionario2;
    private javax.swing.JLabel jLabeCrfFuncionario1;
    private javax.swing.JLabel jLabeCrfFuncionario2;
    private javax.swing.JLabel jLabeCrfFuncionario3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelEspecialidadeFuncionario1;
    private javax.swing.JLabel jLabelNomeFuncionario2;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPaneFuncionario;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCrfFuncionario1;
    private javax.swing.JTextField jTextFieldCrfFuncionario2;
    private javax.swing.JTextField jTextFieldCrfFuncionario3;
    private javax.swing.JTextField jTextFieldCrfFuncionario4;
    private javax.swing.JTextField jTextFieldNomeFuncionario2;
    private javax.swing.JTextField jTextFieldNomeFuncionario3;
    // End of variables declaration//GEN-END:variables

    private void AdicionaNomeMedico() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
