/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JToggleButton;

import enumerate.Especialidade;
import service.ServicoFachada;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

import java.awt.Font;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author Wendler
 */
public class LoginFuncionario extends javax.swing.JFrame {
	/**
	 * Creates new form LoginFuncionario
	 */
	
	public String crf = "";
	public LoginFuncionario() {
		initComponents();
		System.out.println(crf);
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jTextFieldLoginNomeFuncionario = new javax.swing.JTextField();
		jLabelLoginCrfFuncionario1 = new javax.swing.JLabel();
		jTextFieldLoginCrfFuncionario1 = new javax.swing.JTextField();
		jLabelEspecialidadeFuncionario1 = new javax.swing.JLabel();
		jComboBoxLoginEspecialidadeFuncionario1 = new javax.swing.JComboBox();
		jToggleButton1 = new javax.swing.JToggleButton();
		jToggleButton3 = new javax.swing.JToggleButton();
		jLabelLoginNomeFuncionario = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabelLoginCrfFuncionario2 = new javax.swing.JLabel();
		jTextFieldLoginCrfFuncionario2 = new javax.swing.JTextField();
		jToggleButton4 = new javax.swing.JToggleButton();
		jToggleButton5 = new javax.swing.JToggleButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
		
		jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		// jTextFieldLoginNomeFuncionario.setText("Nome");
		jTextFieldLoginNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLoginNomeFuncionarioActionPerformed(evt);
			}
		});

		jLabelLoginCrfFuncionario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabelLoginCrfFuncionario1.setText("Digite o CRF:");

		// jTextFieldLoginCrfFuncionario1.setText("CRF");

		jLabelEspecialidadeFuncionario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabelEspecialidadeFuncionario1.setText("Selecione sua Especialidade");

		ServicoFachada servicoFachada = new ServicoFachada();
		// servicoFachada.cadastrarFuncionario("WENDLER",
		// Especialidade.ACUPUNTURA, "1234");
		// servicoFachada.cadastrarFuncionario("GUILHERME",
		// Especialidade.FISIOTERAPIAMANUAL, "123");
		for (String itemEspecialidade : servicoFachada.getEspecialidades()) {
			jComboBoxLoginEspecialidadeFuncionario1.addItem(itemEspecialidade);
		}
		// jComboBoxLoginEspecialidadeFuncionario1.setSelectedIndex(-1);
		//

		// jComboBoxLoginEspecialidadeFuncionario1.setModel(new
		// javax.swing.DefaultComboBoxModel(
		// new String[] {
		//
		// }));

		jToggleButton1.setText("Cadastrar");
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});

		jToggleButton3.setText("Voltar");
		jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton3ActionPerformed(evt);
			}
		});

		jLabelLoginNomeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

		labelNome = new JLabel();
		labelNome.setText("Nome:");
		labelNome.setFont(new Font("Tahoma", Font.PLAIN, 18));
		// jLabelLoginNomeFuncionario.setText("Digite o Nome");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout
				.createParallelGroup(Alignment.LEADING).addGroup(jPanel1Layout.createSequentialGroup().addGap(30)
						.addGroup(
								jPanel1Layout.createParallelGroup(Alignment.LEADING)
										.addComponent(jTextFieldLoginNomeFuncionario, 471, 471, 471)
										.addComponent(jComboBoxLoginEspecialidadeFuncionario1, 0, 471,
												Short.MAX_VALUE)
										.addComponent(jTextFieldLoginCrfFuncionario1, 471, 471, 471)
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
														.addComponent(jLabelEspecialidadeFuncionario1)
														.addComponent(jLabelLoginCrfFuncionario1))
												.addGap(0, 255, Short.MAX_VALUE))
										.addGroup(jPanel1Layout.createSequentialGroup()
												.addComponent(jLabelLoginNomeFuncionario)
												.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE,
														Short.MAX_VALUE)
												.addComponent(labelNome, GroupLayout.PREFERRED_SIZE, 104,
														GroupLayout.PREFERRED_SIZE)
												.addGap(367)))
						.addGap(30))
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(39).addComponent(jToggleButton1)
						.addPreferredGap(ComponentPlacement.RELATED, 303, Short.MAX_VALUE).addComponent(jToggleButton3)
						.addGap(41)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup()
						.addGroup(jPanel1Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
										.addComponent(jLabelLoginNomeFuncionario))
								.addComponent(labelNome, GroupLayout.PREFERRED_SIZE, 22, GroupLayout.PREFERRED_SIZE))
						.addGap(7)
						.addComponent(jTextFieldLoginNomeFuncionario, GroupLayout.PREFERRED_SIZE, 39,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jLabelLoginCrfFuncionario1)
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jTextFieldLoginCrfFuncionario1, GroupLayout.PREFERRED_SIZE, 39,
								GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(ComponentPlacement.UNRELATED).addComponent(jLabelEspecialidadeFuncionario1)
						.addPreferredGap(ComponentPlacement.UNRELATED)
						.addComponent(jComboBoxLoginEspecialidadeFuncionario1, GroupLayout.PREFERRED_SIZE, 30,
								GroupLayout.PREFERRED_SIZE)
						.addGap(18).addGroup(jPanel1Layout.createParallelGroup(Alignment.BASELINE)
								.addComponent(jToggleButton1).addComponent(jToggleButton3))
						.addContainerGap(32, Short.MAX_VALUE)));
		jPanel1.setLayout(jPanel1Layout);

		jTabbedPane1.addTab("Cadatra Funcionario", jPanel1);

		jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabelLoginCrfFuncionario2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabelLoginCrfFuncionario2.setText("Digite o CRF");

		jTextFieldLoginCrfFuncionario2.setText("CRF");
		jTextFieldLoginCrfFuncionario2.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLoginCrfFuncionario2ActionPerformed(evt);
			}
		});

		jToggleButton4.setText("Login");
		jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton4ActionPerformed(evt);
			}
		});

		jToggleButton5.setText("Cancela");
		jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(jPanel2Layout.createSequentialGroup()
								.addContainerGap().addGroup(jPanel2Layout
										.createParallelGroup(
												javax.swing.GroupLayout.Alignment.LEADING)
										.addGroup(jPanel2Layout.createSequentialGroup()
												.addGroup(jPanel2Layout
														.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(jTextFieldLoginCrfFuncionario2)
														.addGroup(jPanel2Layout.createSequentialGroup()
																.addComponent(jLabelLoginCrfFuncionario2).addGap(0, 413,
																		Short.MAX_VALUE)))
												.addContainerGap())
										.addGroup(jPanel2Layout.createSequentialGroup().addGap(32, 32, 32)
												.addComponent(jToggleButton4)
												.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
														javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
												.addComponent(jToggleButton5).addGap(32, 32, 32)))));
		jPanel2Layout.setVerticalGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel2Layout.createSequentialGroup().addGap(116, 116, 116)
						.addComponent(jLabelLoginCrfFuncionario2).addGap(18, 18, 18)
						.addComponent(jTextFieldLoginCrfFuncionario2, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
						.addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jToggleButton4).addComponent(jToggleButton5))
						.addContainerGap()));

		jTabbedPane1.addTab("Login Funcionario", jPanel2);
		jPanel2.getAccessibleContext().setAccessibleParent(jLabelEspecialidadeFuncionario1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jTabbedPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0,
								0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldLoginNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLoginNomeFuncionarioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldLoginNomeFuncionarioActionPerformed

	private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton3ActionPerformed
		Fisioterapia TelaFisioterapia = new Fisioterapia();
		TelaFisioterapia.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jToggleButton3ActionPerformed

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed
		
		ServicoFachada servicoFachada = new ServicoFachada();
		if (servicoFachada.cadastrarFuncionario(jTextFieldLoginNomeFuncionario.getText(),
				jComboBoxLoginEspecialidadeFuncionario1.getSelectedItem().toString(),
				jTextFieldLoginCrfFuncionario1.getText())) {
			JOptionPane.showMessageDialog(null, "Funcionario Cadastrado com Sucesso!");
			
		}
		else{
			JOptionPane.showMessageDialog(null, "Funcionario ja cadastrado!");
		}

	}

	private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton4ActionPerformed
		ServicoFachada servicoFachada = new ServicoFachada();
		crf = jTextFieldLoginCrfFuncionario2.getText();
		System.out.println(crf);
		if (servicoFachada.solicitarLoginFuncionario(crf)) {
			Funcionario TelaFuncionario = new Funcionario(crf);
			TelaFuncionario.setVisible(true);
			this.dispose();
		}
		else {
			System.out.println(jTextFieldLoginCrfFuncionario2.getText());
			System.out.println("Senha Invalida");
		}
	}// GEN-LAST:event_jToggleButton4ActionPerformed

	public void setjToggleButton4(JToggleButton jToggleButton4) {
		this.jToggleButton4 = jToggleButton4;
	}

	private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton5ActionPerformed
		Fisioterapia TelaFisioterapia = new Fisioterapia();
		TelaFisioterapia.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jToggleButton5ActionPerformed

	private void jTextFieldLoginCrfFuncionario2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLoginCrfFuncionario2ActionPerformed

	}// GEN-LAST:event_jTextFieldLoginCrfFuncionario2ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {

		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>

	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JComboBox jComboBoxLoginEspecialidadeFuncionario1;
	private javax.swing.JLabel jLabelEspecialidadeFuncionario1;
	private javax.swing.JLabel jLabelLoginCrfFuncionario1;
	private javax.swing.JLabel jLabelLoginCrfFuncionario2;
	private javax.swing.JLabel jLabelLoginNomeFuncionario;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextFieldLoginCrfFuncionario1;
	private javax.swing.JTextField jTextFieldLoginCrfFuncionario2;
	private javax.swing.JTextField jTextFieldLoginNomeFuncionario;
	private javax.swing.JToggleButton jToggleButton1;
	private javax.swing.JToggleButton jToggleButton3;
	private javax.swing.JToggleButton jToggleButton4;
	private javax.swing.JToggleButton jToggleButton5;
	private JLabel labelNome;
	// End of variables declaration//GEN-END:variables
}
