/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import service.ServicoFachada;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JOptionPane;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author Wendler
 */
public class LoginPaciente extends javax.swing.JFrame {

	private String cpf;

	public javax.swing.JTextField getjTextFieldLoginCpfPaciente() {
		return jTextFieldLoginCpfPaciente;
	}

	public void setjTextFieldLoginCpfPaciente(javax.swing.JTextField jTextFieldLoginCpfPaciente) {
		this.jTextFieldLoginCpfPaciente = jTextFieldLoginCpfPaciente;
	}

	/**
	 * Creates new form LoginFuncionario
	 */
	public LoginPaciente() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated
	// Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		jTabbedPane1 = new javax.swing.JTabbedPane();
		jPanel1 = new javax.swing.JPanel();
		jTextFieldLoginNomeFuncionario = new javax.swing.JTextField();
		jLabelLoginCrfFuncionario1 = new javax.swing.JLabel();
		jTextFieldLoginCrfFuncionario1 = new javax.swing.JTextField();
		jToggleButton1 = new javax.swing.JToggleButton();
		jToggleButton3 = new javax.swing.JToggleButton();
		jLabelLoginNomeFuncionario = new javax.swing.JLabel();
		jPanel2 = new javax.swing.JPanel();
		jLabelLoginCpfPaciente = new javax.swing.JLabel();
		jTextFieldLoginCpfPaciente = new javax.swing.JTextField();
		jToggleButton4 = new javax.swing.JToggleButton();
		jToggleButton5 = new javax.swing.JToggleButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		// jTextFieldLoginNomeFuncionario.setText("Nome");
		jTextFieldLoginNomeFuncionario.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLoginNomeFuncionarioActionPerformed(evt);
			}
		});

		jLabelLoginCrfFuncionario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabelLoginCrfFuncionario1.setText("Digite o CPF:");

		// jTextFieldLoginCrfFuncionario1.setText("CPF");
		jTextFieldLoginCrfFuncionario1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLoginCrfFuncionario1ActionPerformed(evt);
			}
		});

		jToggleButton1.setText("Cadastrar");
		jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton1ActionPerformed(evt);
			}
		});

		jToggleButton3.setText("Sair");
		jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton3ActionPerformed(evt);
			}
		});

		jLabelLoginNomeFuncionario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabelLoginNomeFuncionario.setText("Digite o Nome:");

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout.setHorizontalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap().addGroup(jPanel1Layout
						.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addComponent(jTextFieldLoginNomeFuncionario).addComponent(jTextFieldLoginCrfFuncionario1)
						.addGroup(jPanel1Layout.createSequentialGroup()
								.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(jLabelLoginCrfFuncionario1)
										.addComponent(jLabelLoginNomeFuncionario))
								.addGap(0, 398, Short.MAX_VALUE)))
						.addContainerGap())
				.addGroup(jPanel1Layout.createSequentialGroup().addGap(39, 39, 39).addComponent(jToggleButton1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
								javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
						.addComponent(jToggleButton3).addGap(27, 27, 27)));
		jPanel1Layout.setVerticalGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(jPanel1Layout.createSequentialGroup().addContainerGap()
						.addComponent(jLabelLoginNomeFuncionario).addGap(18, 18, 18)
						.addComponent(jTextFieldLoginNomeFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jLabelLoginCrfFuncionario1)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
						.addComponent(jTextFieldLoginCrfFuncionario1, javax.swing.GroupLayout.PREFERRED_SIZE, 39,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addGap(92, 92, 92)
						.addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
								.addComponent(jToggleButton1).addComponent(jToggleButton3))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		jTabbedPane1.addTab("Cadatra Paciente", jPanel1);

		jPanel2.setAlignmentX(jLabelLoginCpfPaciente.getAlignmentX());
		jPanel2.setAlignmentY(jLabelLoginCrfFuncionario1.getAlignmentY());
		jPanel2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

		jLabelLoginCpfPaciente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
		jLabelLoginCpfPaciente.setText("Digite o CPF");

		// jTextFieldLoginCpfPaciente.setText("CPF");
		jTextFieldLoginCpfPaciente.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jTextFieldLoginCpfPacienteActionPerformed(evt);
			}
		});

		jToggleButton4.setText("Login");
		jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton4ActionPerformed(evt);
			}
		});

		jToggleButton5.setText("Cancelar");
		jToggleButton5.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				jToggleButton5ActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
		jPanel2Layout.setHorizontalGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING).addGroup(jPanel2Layout
				.createSequentialGroup().addContainerGap()
				.addGroup(jPanel2Layout.createParallelGroup(Alignment.LEADING)
						.addComponent(jTextFieldLoginCpfPaciente, 511, 511, 511).addComponent(jLabelLoginCpfPaciente))
				.addContainerGap())
				.addGroup(Alignment.TRAILING,
						jPanel2Layout.createSequentialGroup().addGap(48).addComponent(jToggleButton4)
								.addPreferredGap(ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
								.addComponent(jToggleButton5).addGap(32)));
		jPanel2Layout
				.setVerticalGroup(
						jPanel2Layout.createParallelGroup(Alignment.LEADING)
								.addGroup(jPanel2Layout.createSequentialGroup().addGap(116)
										.addComponent(jLabelLoginCpfPaciente).addGap(18)
										.addComponent(jTextFieldLoginCpfPaciente, GroupLayout.PREFERRED_SIZE, 39,
												GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
										.addGroup(jPanel2Layout.createParallelGroup(Alignment.BASELINE)
												.addComponent(jToggleButton5).addComponent(jToggleButton4))
										.addContainerGap()));
		jPanel2.setLayout(jPanel2Layout);

		jTabbedPane1.addTab("Login Paciente", jPanel2);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(jTabbedPane1,
						javax.swing.GroupLayout.PREFERRED_SIZE, 536, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0,
								0, Short.MAX_VALUE)));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(
				jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
		setLocationRelativeTo(null);
	}// </editor-fold>//GEN-END:initComponents

	private void jTextFieldLoginNomeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLoginNomeFuncionarioActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldLoginNomeFuncionarioActionPerformed

	private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton1ActionPerformed
		ServicoFachada servicoFachada = new ServicoFachada();
		if (servicoFachada.cadastrarPaciente(jTextFieldLoginNomeFuncionario.getText(),
				jTextFieldLoginCrfFuncionario1.getText())) {
			JOptionPane.showMessageDialog(null, "Paciente Cadastrado com Sucesso!");
		}
		else{
			JOptionPane.showMessageDialog(null, "Este CPF j� foi cadastrado!");
		}
	}

	private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton3ActionPerformed
		Fisioterapia TelaFisioterapia = new Fisioterapia();
		TelaFisioterapia.setVisible(true);
		this.dispose();
	}// GEN-LAST:event_jToggleButton3ActionPerformed

	private void jTextFieldLoginCpfPacienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLoginCpfPacienteActionPerformed

	}// GEN-LAST:event_jTextFieldLoginCpfPacienteActionPerformed

	private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton4ActionPerformed
		ServicoFachada servicoFachada = new ServicoFachada();
		servicoFachada.cadastrarPaciente("Gustavo", "1234");

		if (servicoFachada.solicitarLoginPaciente(jTextFieldLoginCpfPaciente.getText()) != null) {
			Paciente TelaPaciente = new Paciente(jTextFieldLoginCpfPaciente.getText());
			TelaPaciente.setVisible(true);
			this.dispose();
		} else {
			System.out.println(jTextFieldLoginCpfPaciente.getText());
			System.out.println("Senha Invalida");
		}
	}// GEN-LAST:event_jToggleButton4ActionPerformed

	private void jToggleButton5ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jToggleButton5ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jToggleButton5ActionPerformed

	private void jTextFieldLoginCrfFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_jTextFieldLoginCrfFuncionario1ActionPerformed
		// TODO add your handling code here:
	}// GEN-LAST:event_jTextFieldLoginCrfFuncionario1ActionPerformed

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		// <editor-fold defaultstate="collapsed" desc=" Look and feel setting
		// code (optional) ">
		/*
		 * If Nimbus (introduced in Java SE 6) is not available, stay with the
		 * default look and feel. For details see
		 * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.
		 * html
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(LoginPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null,
					ex);
		}
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>
		// </editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new LoginPaciente().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel jLabelLoginCpfPaciente;
	private javax.swing.JLabel jLabelLoginCrfFuncionario1;
	private javax.swing.JLabel jLabelLoginNomeFuncionario;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JTabbedPane jTabbedPane1;
	private javax.swing.JTextField jTextFieldLoginCpfPaciente;
	private javax.swing.JTextField jTextFieldLoginCrfFuncionario1;
	private javax.swing.JTextField jTextFieldLoginNomeFuncionario;
	private javax.swing.JToggleButton jToggleButton1;
	private javax.swing.JToggleButton jToggleButton3;
	private javax.swing.JToggleButton jToggleButton4;
	private javax.swing.JToggleButton jToggleButton5;
	// End of variables declaration//GEN-END:variables
}
