/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Periodo;
import service.ServicoFaixada;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;

/**
 *
 * @author Wendler
 */
public class Paciente extends javax.swing.JFrame {

	private String nomePaciente, cpfPaciente;


    public String getCpfPaciente() {
        return cpfPaciente;
    }

    public void setCpfPaciente(String crfFuncionario) {
        this.cpfPaciente= crfFuncionario;
    }

    public String getNomePaciente() {
        return nomePaciente;
    }

    public void setNomePaciente(String nomeMedico) {
        this.nomePaciente = nomePaciente;
    }
    
    public Paciente(String cpf) {
        setCpfPaciente(cpf);
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPanePaciente = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jTextFieldDataAgendarPaciente = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButtonAgendaConfirmaPaciente = new javax.swing.JButton();
        jButtonAgendaCancelarPaciente = new javax.swing.JButton();
        jComboBoxAgendaEspecialidadeFuncionario = new javax.swing.JComboBox();
        jLabelEspecialidadeFuncionario1 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jTextFieldCrfFuncionario4 = new javax.swing.JTextField();
        jLabeCrfFuncionario3 = new javax.swing.JLabel();
        jButtonConfirmaFuncionario1 = new javax.swing.JButton();
        jButtonCancelarFuncionario1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButtonConfirmaAlteraFuncionario = new javax.swing.JButton();
        jButtonCancelarAlteraFuncionario = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Bem vindo ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(208, Short.MAX_VALUE))
        );

        jTabbedPanePaciente.addTab("Tela Inicial", jPanel2);

        jTextFieldDataAgendarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDataAgendarPacienteActionPerformed(evt);
            }
        });

        jButton1.setText("Verificar Dia");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonAgendaConfirmaPaciente.setText("Confirmar");
        jButtonAgendaConfirmaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaConfirmaPacienteActionPerformed(evt);
            }
        });

        jButtonAgendaCancelarPaciente.setText("Cancelar");
        jButtonAgendaCancelarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaCancelarPacienteActionPerformed(evt);
            }
        });

//        jComboBoxAgendaEspecialidadeFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laura Miller - Muscular", "Lucas Ribeiro - Pilates", "Carla Roberta - Fisioterapeuta Manual", "Riana Stuart - Acunpultura" }));
//        jComboBoxAgendaEspecialidadeFuncionario.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jComboBoxAgendaEspecialidadeFuncionarioActionPerformed(evt);
//            }
//        });

        ServicoFaixada servicoFachada = new ServicoFaixada();
		// servicoFachada.cadastrarFuncionario("WENDLER",
		// Especialidade.ACUPUNTURA, "1234");
		// servicoFachada.cadastrarFuncionario("GUILHERME",
		// Especialidade.FISIOTERAPIAMANUAL, "123");
        for(entity.Funcionario itemFuncionario : servicoFachada.getFuncionarios()){
			String opcaoEspecialidade = itemFuncionario.getNome().toString() + " - " + itemFuncionario.getEspecialidade().toString() + " - " + itemFuncionario.getCrf();
			jComboBoxAgendaEspecialidadeFuncionario.addItem(opcaoEspecialidade);	
		}
		jComboBoxAgendaEspecialidadeFuncionario.setSelectedIndex(-1);
		
        jLabelEspecialidadeFuncionario1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelEspecialidadeFuncionario1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelEspecialidadeFuncionario1.setText("Selecione sua Especialidade");

        //String teste = jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem().toString();
		//String[] arrayTeste = teste.split("Gustavo - ACUPUNTURA - 1234");
		entity.Funcionario funcionario = servicoFachada.solicitarFuncionarioByCrf("");
		for (Periodo itemPeriodo : servicoFachada.IniciarAgendamento(funcionario).getPeriodos()) {
			//comboBoxHorariosDisponiveis.addItem(itemPeriodo.getInicio() + " h às " + itemPeriodo.getFim() + "h");
		}
//        jComboBoxAgendaHoraFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laura Miller - Muscular", "Lucas Ribeiro - Pilates", "Carla Roberta - Fisioterapeuta Manual", "Riana Stuart - Acunpultura" }));
//        jComboBoxAgendaHoraFuncionario.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jComboBoxAgendaHoraFuncionarioActionPerformed(evt);
//            }
//        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11Layout.setHorizontalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel11Layout.createSequentialGroup()
        					.addGap(29)
        					.addGroup(jPanel11Layout.createParallelGroup(Alignment.LEADING, false)
        						.addGroup(jPanel11Layout.createSequentialGroup()
        							.addComponent(jButtonAgendaConfirmaPaciente)
        							.addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        							.addComponent(jButtonAgendaCancelarPaciente))
        						.addComponent(jComboBoxAgendaEspecialidadeFuncionario, 0, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        						.addComponent(jLabelEspecialidadeFuncionario1, GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)))
        				.addGroup(jPanel11Layout.createSequentialGroup()
        					.addGap(103)
        					.addGroup(jPanel11Layout.createParallelGroup(Alignment.LEADING, false)
        						.addComponent(jTextFieldDataAgendarPaciente, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        						.addComponent(jButton1, GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))))
        			.addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addGap(20)
        			.addComponent(jLabelEspecialidadeFuncionario1)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addComponent(jComboBoxAgendaEspecialidadeFuncionario, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jTextFieldDataAgendarPaciente, GroupLayout.PREFERRED_SIZE, 29, GroupLayout.PREFERRED_SIZE)
        			.addGap(9)
        			.addComponent(jButton1)
        			.addPreferredGap(ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButtonAgendaCancelarPaciente)
        				.addComponent(jButtonAgendaConfirmaPaciente))
        			.addContainerGap())
        );
        jPanel11.setLayout(jPanel11Layout);

        jTabbedPanePaciente.addTab("Agendar", jPanel11);

        jTextFieldCrfFuncionario4.setText("Nome Paciente");
        jTextFieldCrfFuncionario4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCrfFuncionario4ActionPerformed(evt);
            }
        });

        jLabeCrfFuncionario3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabeCrfFuncionario3.setText("Digite o nome do Paciente");

        jButtonConfirmaFuncionario1.setText("Confirmar");
        jButtonConfirmaFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaFuncionario1ActionPerformed(evt);
            }
        });

        jButtonCancelarFuncionario1.setText("Cancelar");
        jButtonCancelarFuncionario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarFuncionario1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel15Layout.createSequentialGroup()
                        .addComponent(jButtonConfirmaFuncionario1)
                        .addGap(112, 112, 112)
                        .addComponent(jButtonCancelarFuncionario1))
                    .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabeCrfFuncionario3)
                        .addComponent(jTextFieldCrfFuncionario4, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jLabeCrfFuncionario3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCrfFuncionario4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132)
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaFuncionario1)
                    .addComponent(jButtonCancelarFuncionario1))
                .addGap(20, 20, 20))
        );

        jTabbedPanePaciente.addTab("Avaliação de Atendimento", jPanel15);

        jButtonConfirmaAlteraFuncionario.setText("Alterar");
        jButtonConfirmaAlteraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaAlteraFuncionarioActionPerformed(evt);
            }
        });

        jButtonCancelarAlteraFuncionario.setText("Cancelar");
        jButtonCancelarAlteraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarAlteraFuncionarioActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jButtonConfirmaAlteraFuncionario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 218, Short.MAX_VALUE)
                        .addComponent(jButtonCancelarAlteraFuncionario)))
                .addGap(30, 30, 30))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 199, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConfirmaAlteraFuncionario)
                    .addComponent(jButtonCancelarAlteraFuncionario))
                .addGap(20, 20, 20))
        );

        jTabbedPanePaciente.addTab("Altera Hora Marcada", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePaciente)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButtonConfirmaAlteraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        // TODO add your handling code here:
    }                                                                

    private void jButtonCancelarAlteraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                                 
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }                                                                

    private void jTextFieldCrfFuncionario4ActionPerformed(java.awt.event.ActionEvent evt) {                                                          
        // TODO add your handling code here:
    }                                                         

    private void jButtonConfirmaFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        // TODO add your handling code here:
    }                                                           

    private void jButtonCancelarFuncionario1ActionPerformed(java.awt.event.ActionEvent evt) {                                                            
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }                                                           

    private void jTextFieldDataAgendarPacienteActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        // TODO add your handling code here:
    }                                                             

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        
        new Picker().chamaCalendario(jTextFieldDataAgendarPaciente);
    }                                        

    private void jButtonAgendaConfirmaPacienteActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        //String stringDoComboBox;
        //stringDoComboBox = String.valueOf(jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem());
        //Agendar telaAgendar = new Agendar(jTextFieldDataAgendarPaciente.getText().toString(), jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem().toString());
    	Agendar telaAgendar = new Agendar(this.jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem().toString());
    	telaAgendar.setVisible(true);
        
        
    
    }                                                             

    private void jButtonAgendaCancelarPacienteActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        Fisioterapia TelaFisioterapia = new Fisioterapia();
        TelaFisioterapia.setVisible(true);
        this.dispose();
    }                                                             

    private void jComboBoxAgendaEspecialidadeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                                        
        // TODO add your handling code here:
    }                                                                       

    private void jComboBoxAgendaHoraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    
    
    public static void main(String args[]) {
 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Paciente().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonAgendaCancelarPaciente;
    private javax.swing.JButton jButtonAgendaConfirmaPaciente;
    private javax.swing.JButton jButtonCancelarAlteraFuncionario;
    private javax.swing.JButton jButtonCancelarFuncionario1;
    private javax.swing.JButton jButtonConfirmaAlteraFuncionario;
    private javax.swing.JButton jButtonConfirmaFuncionario1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBoxAgendaEspecialidadeFuncionario;
    private javax.swing.JLabel jLabeCrfFuncionario3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelEspecialidadeFuncionario1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPanePaciente;
    private javax.swing.JTextField jTextFieldCrfFuncionario4;
    private javax.swing.JTextField jTextFieldDataAgendarPaciente;
    // End of variables declaration                   

}
