/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import entity.Periodo;
import service.ServicoFachada;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.GroupLayout;
import javax.swing.JButton;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;
import javax.swing.SwingConstants;

import aggregate.AgendaPaciente;

import java.awt.Font;
import java.awt.Dimension;
import javax.swing.JLabel;

/**
 *
 * @author Wendler
 */
public class Paciente extends javax.swing.JFrame {

	private String nomePaciente, cpfPaciente;


    public String getCpfPaciente() {
        return cpfPaciente;
    }

    public void setCpfPaciente(String crfFuncionario) {
        this.cpfPaciente= crfFuncionario;
    }

    public String getNomePaciente() {
        return nomePaciente;
    }

    public void setNomePaciente(String nomeMedico) {
        this.nomePaciente = nomePaciente;
    }
    
    public Paciente(String cpf) {
        setCpfPaciente(cpf);
    	initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTabbedPanePaciente = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabelTelaInicialPaciente = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jButtonAgendaConfirmaPaciente = new javax.swing.JButton();
        jComboBoxAgendaEspecialidadeFuncionario = new javax.swing.JComboBox();
        jComboBoxAgendaEspecialidadeFuncionario.setPreferredSize(new Dimension(29, 20));
        jLabelEspecialidadeFuncionario1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jButtonConfirmaAlteraFuncionario = new javax.swing.JButton();
        jComboBoxCancelaHoraPaciente = new javax.swing.JComboBox();
        jComboBoxCancelaHoraPaciente.setPreferredSize(new Dimension(29, 20));

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTelaInicialPaciente.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabelTelaInicialPaciente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTelaInicialPaciente.setText("Bem Vindo ");
        
        JButton btnLogoff = new JButton("Logoff");
        btnLogoff.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent arg0) {
        		Fisioterapia telaFisioterapia = new Fisioterapia();
        		telaFisioterapia.setVisible(true);
        		telaFisioterapia.setLocationRelativeTo(null);
        		dispose();
        	}
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2Layout.setHorizontalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addContainerGap(38, Short.MAX_VALUE)
        			.addComponent(jLabelTelaInicialPaciente, GroupLayout.PREFERRED_SIZE, 352, GroupLayout.PREFERRED_SIZE)
        			.addGap(28))
        		.addGroup(Alignment.LEADING, jPanel2Layout.createSequentialGroup()
        			.addGap(178)
        			.addComponent(btnLogoff)
        			.addContainerGap(177, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
        	jPanel2Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel2Layout.createSequentialGroup()
        			.addGap(73)
        			.addComponent(jLabelTelaInicialPaciente, GroupLayout.PREFERRED_SIZE, 54, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 163, Short.MAX_VALUE)
        			.addComponent(btnLogoff)
        			.addGap(22))
        );
        jPanel2.setLayout(jPanel2Layout);

        jTabbedPanePaciente.addTab("Tela Inicial", jPanel2);

        jButtonAgendaConfirmaPaciente.setText("Confirmar");
        jButtonAgendaConfirmaPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaConfirmaPacienteActionPerformed(evt);
            }
        });

//        jComboBoxAgendaEspecialidadeFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laura Miller - Muscular", "Lucas Ribeiro - Pilates", "Carla Roberta - Fisioterapeuta Manual", "Riana Stuart - Acunpultura" }));
//        jComboBoxAgendaEspecialidadeFuncionario.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jComboBoxAgendaEspecialidadeFuncionarioActionPerformed(evt);
//            }
//        });

        ServicoFachada servicoFachada = new ServicoFachada();
		// servicoFachada.cadastrarFuncionario("WENDLER",
		// Especialidade.ACUPUNTURA, "1234");
		// servicoFachada.cadastrarFuncionario("GUILHERME",
		// Especialidade.FISIOTERAPIAMANUAL, "123");
        for(entity.Funcionario itemFuncionario : servicoFachada.getFuncionarios()){
			String opcaoEspecialidade = itemFuncionario.getNome().toString() + " - " + itemFuncionario.getEspecialidade().toString() + " - " + itemFuncionario.getCrf();
			jComboBoxAgendaEspecialidadeFuncionario.addItem(opcaoEspecialidade);	
		}
		jComboBoxAgendaEspecialidadeFuncionario.setSelectedIndex(-1);
		
        jLabelEspecialidadeFuncionario1.setFont(new Font("Tahoma", Font.BOLD, 12)); // NOI18N
        jLabelEspecialidadeFuncionario1.setHorizontalAlignment(SwingConstants.LEFT);
        jLabelEspecialidadeFuncionario1.setText("Selecione a Especialidade");

        //String teste = jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem().toString();
		//String[] arrayTeste = teste.split("Gustavo - ACUPUNTURA - 1234");
		entity.Funcionario funcionario = servicoFachada.solicitarFuncionarioByCrf("");
		for (Periodo itemPeriodo : servicoFachada.IniciarAgendamento(funcionario).getPeriodos()) {
			//comboBoxHorariosDisponiveis.addItem(itemPeriodo.getInicio() + " h �s " + itemPeriodo.getFim() + "h");
		}
//        jComboBoxAgendaHoraFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Laura Miller - Muscular", "Lucas Ribeiro - Pilates", "Carla Roberta - Fisioterapeuta Manual", "Riana Stuart - Acunpultura" }));
//        jComboBoxAgendaHoraFuncionario.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jComboBoxAgendaHoraFuncionarioActionPerformed(evt);
//            }
//        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11Layout.setHorizontalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.TRAILING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addContainerGap(171, Short.MAX_VALUE)
        			.addComponent(jButtonAgendaConfirmaPaciente)
        			.addGap(168))
        		.addGroup(Alignment.LEADING, jPanel11Layout.createSequentialGroup()
        			.addGap(29)
        			.addGroup(jPanel11Layout.createParallelGroup(Alignment.LEADING)
        				.addComponent(jComboBoxAgendaEspecialidadeFuncionario, GroupLayout.PREFERRED_SIZE, 363, GroupLayout.PREFERRED_SIZE)
        				.addComponent(jLabelEspecialidadeFuncionario1, GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))
        			.addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
        	jPanel11Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel11Layout.createSequentialGroup()
        			.addGap(90)
        			.addComponent(jLabelEspecialidadeFuncionario1)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jComboBoxAgendaEspecialidadeFuncionario, GroupLayout.PREFERRED_SIZE, 30, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 155, Short.MAX_VALUE)
        			.addComponent(jButtonAgendaConfirmaPaciente)
        			.addContainerGap())
        );
        jPanel11.setLayout(jPanel11Layout);

        jTabbedPanePaciente.addTab("Agendar", jPanel11);

        jButtonConfirmaAlteraFuncionario.setText("Alterar");
        jButtonConfirmaAlteraFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmaAlteraFuncionarioActionPerformed(evt);
            }
        });	

         /*jComboBoxCancelaHoraPaciente.
        	for(AgendaPaciente agendaPaciente : servicoFachada.getAgendaPaciente()){
        		if(agendaPaciente.getPaciente().getCpf().equals(servicoFachada.solicitarLoginPaciente(jTextFieldLoginCpfPaciente.getText())) ){
        			
        		}
        	}*/
        	
        
        //setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        
        JLabel lblSelecioneOAgendamento = new JLabel();
        lblSelecioneOAgendamento.setText("Selecione o Agendamento");
        lblSelecioneOAgendamento.setHorizontalAlignment(SwingConstants.LEFT);
        lblSelecioneOAgendamento.setFont(new Font("Tahoma", Font.BOLD, 12));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6Layout.setHorizontalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(172)
        					.addComponent(jButtonConfirmaAlteraFuncionario))
        				.addGroup(jPanel6Layout.createSequentialGroup()
        					.addGap(23)
        					.addGroup(jPanel6Layout.createParallelGroup(Alignment.LEADING)
        						.addComponent(jComboBoxCancelaHoraPaciente, GroupLayout.PREFERRED_SIZE, 366, GroupLayout.PREFERRED_SIZE)
        						.addComponent(lblSelecioneOAgendamento, GroupLayout.PREFERRED_SIZE, 379, GroupLayout.PREFERRED_SIZE))))
        			.addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
        	jPanel6Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel6Layout.createSequentialGroup()
        			.addGap(83)
        			.addComponent(lblSelecioneOAgendamento, GroupLayout.PREFERRED_SIZE, 15, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.UNRELATED)
        			.addComponent(jComboBoxCancelaHoraPaciente, GroupLayout.PREFERRED_SIZE, 31, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED, 161, Short.MAX_VALUE)
        			.addComponent(jButtonConfirmaAlteraFuncionario)
        			.addContainerGap())
        );
        jPanel6.setLayout(jPanel6Layout);

        jTabbedPanePaciente.addTab("Cancelar Agendamento", jPanel6);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPanePaciente)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void jButtonConfirmaAlteraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {   
    	
        
    }                                                                

    private void jButtonAgendaConfirmaPacienteActionPerformed(java.awt.event.ActionEvent evt) {                                                              
        //String stringDoComboBox;
        //stringDoComboBox = String.valueOf(jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem());
        //Agendar telaAgendar = new Agendar(jTextFieldDataAgendarPaciente.getText().toString(), jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem().toString());
    	Agendar telaAgendar = new Agendar(this.jComboBoxAgendaEspecialidadeFuncionario.getSelectedItem().toString());
    	telaAgendar.setVisible(true);
        
        
    
    }                                                             

    private void jComboBoxAgendaEspecialidadeFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                                        
        // TODO add your handling code here:
    }                                                                       

    private void jComboBoxAgendaHoraFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {                                                               
        // TODO add your handling code here:
    }                                                              

    
    
    public static void main(String args[]) {
 
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Paciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Paciente().setVisible(true);
//            }
//        });
    }
    private javax.swing.JButton jButtonAgendaConfirmaPaciente;
    private javax.swing.JButton jButtonConfirmaAlteraFuncionario;
    private javax.swing.JComboBox jComboBoxCancelaHoraPaciente;
    private javax.swing.JComboBox jComboBoxAgendaEspecialidadeFuncionario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTelaInicialPaciente;
    private javax.swing.JLabel jLabelEspecialidadeFuncionario1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTabbedPane jTabbedPanePaciente;
}
